# we will use openjdk 16 with alpine as it is a very small linux distro
FROM  adoptopenjdk/openjdk11:alpine-jre

# copy the packaged jar file into our docker image
COPY target/shopping-cart-service-0.0.1-SNAPSHOT.jar /shopping-cart-service.jar
RUN ls
# set the startup command to execute the jar
CMD ["java", "-jar", "/shopping-cart-service.jar"]