# we will use openjdk 16 with alpine as it is a very small linux distro
FROM adoptopenjdk/openjdk11:alpine-jre
LABEL maintainer="Naveen"
COPY /target/product-catalog-service-0.0.1-SNAPSHOT.jar /home/product-catalog-service.jar
CMD ["java","-jar","/home/product-catalog-service.jar"]
