# we will use openjdk 16 with alpine as it is a very small linux distro
FROM  adoptopenjdk/openjdk11:alpine-jre

# copy the packaged jar file into our docker image
WORKDIR /opt/docker
RUN ls
# set the startup command to execute the jar
CMD ["java", "-jar", "/product-catalog-service.jar"]
