#!groovy
pipeline {
  agent none
  stages {    
stage('Maven Install') {
     agent {        
docker {          
image 'maven:3.5.0'
image 'openjdk:11-jdk'
}      
}      
steps {
      sh 'pwd'
      sh 'java -version'
      dir('product-catalog') {
      sh 'pwd'
      sh 'mvn clean install'
      }
      }
    }
   }
}
